### ISSUE TITLE
Clarify `InvRef` definition

### ISSUE THREAD

**Issue by lua-rocks** [minetest-toolkit/minetest-lsp-api#10]
According to our documentation, `InvRef` should look like this:

```lua
mt.InvRef {
    add_item: function,
    allow_metadata_inventory_move: function,
    allow_metadata_inventory_put: function,
    allow_metadata_inventory_take: function,
    allow_move: function,
    allow_put: function,
    allow_take: function,
    contains_item: function,
    get_list: function,
    get_lists: function,
    get_location: function,
    get_size: function,
    get_stack: function,
    get_width: function,
    is_empty: function,
    on_metadata_inventory_move: function,
    on_metadata_inventory_put: function,
    on_metadata_inventory_take: function,
    on_move: function,
    on_put: function,
    on_take: function,
    remove_item: function,
    room_for_item: function,
    set_list: function,
    set_lists: function,
    set_size: function,
    set_stack: function,
    set_width: function,
}
```

But in Minetest 5.7 it actually looks like this:

```lua
userdata metatable: {
        get_size = <function>,
        get_list = <function>,
        get_lists = <function>,
        get_width = <function>,
        get_location = <function>,
        add_item = <function>,
        remove_item = <function>,
        room_for_item = <function>,
        contains_item = <function>,
        is_empty = <function>,
        set_lists = <function>,
        set_list = <function>,
        set_size = <function>,
        set_stack = <function>,
        set_width = <function>,
        get_stack = <function>
}
```

There is no `allow_*` and `on_*` functions.

**Comment by lua-rocks** [comment]
Okay, I get it! They are only available in detached & nodemeta inventories.

**Comment by lua-rocks** [comment]
Hmm... Chest's inventory looks like this:

```lua
userdata metatable: {
        get_size = <function>,
        get_list = <function>,
        get_lists = <function>,
        get_width = <function>,
        get_location = <function>,
        add_item = <function>,
        remove_item = <function>,
        room_for_item = <function>,
        contains_item = <function>,
        is_empty = <function>,
        set_lists = <function>,
        set_list = <function>,
        set_size = <function>,
        set_stack = <function>,
        set_width = <function>,
        get_stack = <function>
}
```

It doesn't have these functions too...

**Comment by lua-rocks** [comment]
WHY? 🤨 Are they nil by default and I have to define them manually?

**Comment by lua-rocks** [comment]
https://github.com/minetest/minetest/blob/2e497cc4717f4b0f9ebed4b4df725031a55a3f4b/doc/lua_api.txt#L6823-L6841

**Comment by lua-rocks** [comment]
Hmm... Looks like these calbacks are part of node definition, but not a noderef.

**Comment by lua-rocks** [comment]
... Nope :( That's not true either.

**Comment by lua-rocks** [comment]
@AFCMS help! :D

**Comment by lua-rocks** [comment]
I inspected MTG and found them in detached inventory definitions. There's no problem with that, but how about nodes?

**Comment by AFCMS** [comment]
These functions are in the node definition for node inventories and they are passed as a table when calling `minetest.create_detached_inventory`

https://github.com/minetest/minetest/blob/2e497cc4717f4b0f9ebed4b4df725031a55a3f4b/doc/lua_api.txt#L9495-L9521

**Comment by AFCMS** [comment]
The fact that these functions are explained in a section right after the InvRef section is misleading.

**Comment by lua-rocks** [comment]
It says [here](https://github.com/minetest/minetest/blob/2e497cc4717f4b0f9ebed4b4df725031a55a3f4b/doc/lua_api.txt#LL6825C8-L6825C8) that "**`detached`** & **`nodemeta`** inventories provide the following callbacks".

As far as I understand it, detached inventory has nothing to do with a node, its detached!

... And nodemeta is even more mysterious to me.

**Comment by lua-rocks** [comment]
I removed all callbacks definitions from InvRef and NodeDef, and combined them all into DetachedInvDef.

I think, if they belong to classes other than DetachedInvDef, these classes must inherit from it.

**Comment by lua-rocks** [comment]
I'm closing this issue. Feel free to reopen it if you think that I did something wrong.

**Comment by AFCMS** [comment]
> It says [here](https://github.com/minetest/minetest/blob/2e497cc4717f4b0f9ebed4b4df725031a55a3f4b/doc/lua_api.txt#LL6825C8-L6825C8) that "**`detached`** & **`nodemeta`** inventories provide the following callbacks".
> 
> As far as I understand it, detached inventory has nothing to do with a node, its detached!
> 
> ... And nodemeta is even more mysterious to me.

For node inventories, the callbacks are defined in node definition.

https://github.com/minetest/minetest/blob/2e497cc4717f4b0f9ebed4b4df725031a55a3f4b/doc/lua_api.txt#L8746-L8765

For detached inventories I have no idea if these callback functions are present in the returned InvRef.

https://github.com/minetest/minetest/blob/2e497cc4717f4b0f9ebed4b4df725031a55a3f4b/doc/lua_api.txt#L5876
https://github.com/minetest/minetest/blob/2e497cc4717f4b0f9ebed4b4df725031a55a3f4b/doc/lua_api.txt#L9495-L9521

**Comment by lua-rocks** [comment]
Ok, thanks! I'll test callbacks in node definition tomorrow.

**Comment by lua-rocks** [comment]
This code doesn't work:

```lua
local function log(any) minetest.log(dump(any)) end

minetest.register_on_mods_loaded(function()
  local node_def = minetest.registered_nodes["default:chest"]
  function node_def.on_take() log "take" end
  function node_def.on_put() log "put" end
end)
```

**Comment by AFCMS** [comment]
> This code doesn't work:
> 
> ```lua
> local function log(any) minetest.log(dump(any)) end
> 
> minetest.register_on_mods_loaded(function()
>   local node_def = minetest.registered_nodes["default:chest"]
>   function node_def.on_take() log "take" end
>   function node_def.on_put() log "put" end
> end)
> ```

The function names should be `on_metadata_inventory_take` and `on_metadata_inventory_put`

**Comment by lua-rocks** [comment]
> The function names should be `on_metadata_inventory_take` and `on_metadata_inventory_put`

Doesn't work anyway.

**Comment by lua-rocks** [comment]
And this also not working:

```lua
minetest.override_item(
  "default:chest",
  { on_metadata_inventory_take = function() log "take" end }
)
```

**Comment by lua-rocks** [comment]
At the moment, these callbacks are declared only in `DetachedInvDef`, used by the function `minetest.create_detached_inventory` and in my experience that is the only place where they work. But this is not consistent with the documentation. Something I don't understand.

**Comment by AFCMS** [comment]
You should look how its used in real games/mods then. Its often more clear than the docs.

**Comment by AFCMS** [comment]
I am really unsure about DetachedInvRef, are you actually sure the callbacks are present in the returned object?

**Comment by AFCMS** [comment]
Here is how I understood the docs:

https://github.com/AFCMS/minetest_vscode_lua/blob/eb4a53daccda0d6eea38369a559ab4d5dff0c0ea/api/inventory.lua#L9-L36

https://github.com/AFCMS/minetest_vscode_lua/blob/eb4a53daccda0d6eea38369a559ab4d5dff0c0ea/types/node_definition.lua#L570-L588

**Comment by lua-rocks** [comment]
https://github.com/minetest-toolkit/minetest_game/blob/5c3b8705426bf6406a008759c87077cdf0c96775/mods/creative/inventory.lua#L128-L137C3

This corresponds to the current headers.

**Comment by lua-rocks** [comment]
And this: https://github.com/minetest-toolkit/minetest_game/blob/5c3b8705426bf6406a008759c87077cdf0c96775/mods/creative/inventory.lua#L33-L59

**Comment by AFCMS** [comment]
This is quite wrong: https://github.com/minetest-toolkit/minetest-lsp-api/blob/6812a0205f1dfe57df61ee5ab2da0771bc220bf8/api/definitions/detached.lua

The `*_metadata_inventory_*` functions are only for node definition and do not work when passed to `create_detached_inventory`:

https://git.minetest.land/MineClone2/MineClone2/src/commit/3b64ceb5b21e6a9afc824a23fc59a84ef1cd96a9/mods/ITEMS/mcl_chests/init.lua#L458-L478

The other functions are right.

You should just move the wrong functions to node definition to fix I think.

**Comment by lua-rocks** [comment]
Ok, but I still need some example how it works in node definition.

**Comment by lua-rocks** [comment]
Oh, I didn't notice, you just showed this example, nice :)

But it's too complicated. I need something simpler to test for myself.

... Okay, I'll experiment with it tomorrow.

**Comment by lua-rocks** [comment]
By the way, recently I published my first mod 🥳 [check it out](https://content.minetest.net/packages/luarocks/simple_woodcutter)!

I don't think it has a better alternative! It is 100 times simpler than all similar mods and works with trees of absolutely any shape/size.

**Comment by lua-rocks** [comment]
You are right.

I just checked experimentally that `on_*` doesn't work in nodes, but works in detached;

The same way `on_metadata_*` doesn't work in detached, but does in nodes.

**Comment by lua-rocks** [comment]
```
### Callbacks

Detached & nodemeta inventories provide the following callbacks for move actions:

#### Before

The `allow_*` callbacks return how many items can be moved.

* `allow_move`/`allow_metadata_inventory_move`: Moving items in the inventory
* `allow_take`/`allow_metadata_inventory_take`: Taking items from the inventory
* `allow_put`/`allow_metadata_inventory_put`: Putting items to the inventory

#### After

The `on_*` callbacks are called after the items have been placed in the inventories.

* `on_move`/`on_metadata_inventory_move`: Moving items in the inventory
* `on_take`/`on_metadata_inventory_take`: Taking items from the inventory
* `on_put`/`on_metadata_inventory_put`: Putting items to the inventory
```

What is meant here is that all functions to the left of the slash are for detached only, and those to the right are for nodemeta only.

**Comment by lua-rocks** [comment]
I still don't quite understand why it says nodemeta and not nodedef.

Does nodedef extends from nodemeta?

**Comment by AFCMS** [comment]
> I still don't quite understand why it says nodemeta and not nodedef.
> 
> Does nodedef extends from nodemeta?

I think the documentation is unclear, node meta is per-node data storage, node def is the definition of a node (nodedef doesn't extend from nodemeta).
