### ISSUE TITLE
Some minetest functions are listed in the documentation, but do not exist

### ISSUE THREAD

**Issue by lua-rocks** [minetest-toolkit/minetest-lsp-api#9]
@AFCMS I [commented](https://github.com/minetest-toolkit/minetest-lsp-api/commit/906a18d3e2f58b53fdc8226489fc6d70ad0db773) functions `minetest.dir_to_fourdir` and `minetest.fourdir_to_dir`. They are documented but equals `nil`. I have no idea why.

**Comment by AFCMS** [comment]
Confirmed. Maybe thats a merge problem on the Minetest side.

**Comment by appgurueu** [comment]
These functions do very much exist (see `builtin/item_s.lua`). Perhaps you were testing on an older (pre-5.7) version but using the 5.7(-dev?) docs?

**Comment by lua-rocks** [comment]
@appgurueu Hmm... I was sure these functions were present in the old documentation (7ffc0268), but now I reviewed it and they are really not there. I confirm that they are present in the 5.7. Thank you!
